services:
  erc20_notify_bot:
    build: .
    volumes:
      - .:/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ERC20_TOKEN_ADDRESS=${ERC20_TOKEN_ADDRESS}
      - ETH_RPC_URL=${ETH_RPC_URL}
